//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GvcRevitPlugins.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double borderGridsOffset {
            get {
                return ((double)(this["borderGridsOffset"]));
            }
            set {
                this["borderGridsOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int viewInSheetJustification {
            get {
                return ((int)(this["viewInSheetJustification"]));
            }
            set {
                this["viewInSheetJustification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int viewInSheetAlignment {
            get {
                return ((int)(this["viewInSheetAlignment"]));
            }
            set {
                this["viewInSheetAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double viewInSheetHorizontalOffset {
            get {
                return ((double)(this["viewInSheetHorizontalOffset"]));
            }
            set {
                this["viewInSheetHorizontalOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double viewInSheetVerticalOffset {
            get {
                return ((double)(this["viewInSheetVerticalOffset"]));
            }
            set {
                this["viewInSheetVerticalOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sheetsPageExecuteFloorCommand {
            get {
                return ((bool)(this["sheetsPageExecuteFloorCommand"]));
            }
            set {
                this["sheetsPageExecuteFloorCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sheetsPageExecuteGridsCommand {
            get {
                return ((bool)(this["sheetsPageExecuteGridsCommand"]));
            }
            set {
                this["sheetsPageExecuteGridsCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int coordinatesType {
            get {
                return ((int)(this["coordinatesType"]));
            }
            set {
                this["coordinatesType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grossVolumeParameter {
            get {
                return ((string)(this["grossVolumeParameter"]));
            }
            set {
                this["grossVolumeParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string netVolumeParameter {
            get {
                return ((string)(this["netVolumeParameter"]));
            }
            set {
                this["netVolumeParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool getAllElementsOfTypeIsChecked {
            get {
                return ((bool)(this["getAllElementsOfTypeIsChecked"]));
            }
            set {
                this["getAllElementsOfTypeIsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool grossVolumeParameterToggleIsChecked {
            get {
                return ((bool)(this["grossVolumeParameterToggleIsChecked"]));
            }
            set {
                this["grossVolumeParameterToggleIsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool netVolumeParameterToggleIsChecked {
            get {
                return ((bool)(this["netVolumeParameterToggleIsChecked"]));
            }
            set {
                this["netVolumeParameterToggleIsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double platformElevation {
            get {
                return ((double)(this["platformElevation"]));
            }
            set {
                this["platformElevation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double minimumDistance {
            get {
                return ((double)(this["minimumDistance"]));
            }
            set {
                this["minimumDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double terrainCheckCalcDistance {
            get {
                return ((double)(this["terrainCheckCalcDistance"]));
            }
            set {
                this["terrainCheckCalcDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double terrainCheckCalcHeight {
            get {
                return ((double)(this["terrainCheckCalcHeight"]));
            }
            set {
                this["terrainCheckCalcHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double terrainCheckStrucWallHeight {
            get {
                return ((double)(this["terrainCheckStrucWallHeight"]));
            }
            set {
                this["terrainCheckStrucWallHeight"] = value;
            }
        }
    }
}
